// HomeScreenStyle.js
import { StyleSheet, Platform } from 'react-native';
import { COLOR, FONT, RADIUS, WINDOW_WIDTH as W } from './theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLOR.bgPage,
  },

  // ── Header ───────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: COLOR.tealDeep,
    paddingTop: Platform.OS === 'ios' ? 60 : 44,
    paddingBottom: 24,
    paddingHorizontal: 24,
    borderBottomLeftRadius: RADIUS.xl,
    borderBottomRightRadius: RADIUS.xl,
    overflow: 'hidden',
  },
  headerBlob: {
    position: 'absolute',
    top: -W * 0.2,
    right: -W * 0.15,
    width: W * 0.55,
    height: W * 0.55,
    borderRadius: W * 0.275,
    backgroundColor: 'rgba(10,155,170,0.13)',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  headerGreeting: {
    fontFamily: FONT.sans,
    fontSize: 13,
    color: 'rgba(255,255,255,0.55)',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  headerName: {
    fontFamily: FONT.serif,
    fontSize: 26,
    color: COLOR.white,
    letterSpacing: -0.4,
    marginTop: 2,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.sm,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Scroll ────────────────────────────────────────────────────────────────────
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 48,
  },

  // ── Translator Card ───────────────────────────────────────────────────────────
  translatorCard: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.xl,
    padding: 20,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardIconWrap: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontFamily: FONT.serif,
    fontSize: 17,
    color: COLOR.inkPrimary,
    letterSpacing: -0.2,
  },
  cardSub: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    marginTop: 1,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 100,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: COLOR.borderIdle,
  },
  liveBadgeActive: {
    backgroundColor: 'rgba(34,197,94,0.10)',
    borderColor: 'rgba(34,197,94,0.25)',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#CBD5E1',
  },
  liveDotActive: { backgroundColor: '#22C55E' },
  liveText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 0.8,
  },
  liveTextActive: { color: '#16A34A' },
  viewfinderWrap: { marginBottom: 14 },
  viewfinder: {
    height: 200,
    borderRadius: RADIUS.lg,
    backgroundColor: '#0D2B2E',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.20)',
  },
  corner: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderColor: COLOR.tealLight,
    borderWidth: 2,
  },
  cornerTL: { top: 14, left: 14,  borderRightWidth: 0,  borderBottomWidth: 0, borderTopLeftRadius: 4 },
  cornerTR: { top: 14, right: 14, borderLeftWidth: 0,   borderBottomWidth: 0, borderTopRightRadius: 4 },
  cornerBL: { bottom: 14, left: 14,  borderRightWidth: 0, borderTopWidth: 0, borderBottomLeftRadius: 4 },
  cornerBR: { bottom: 14, right: 14, borderLeftWidth: 0,  borderTopWidth: 0, borderBottomRightRadius: 4 },
  viewfinderCenter: { alignItems: 'center', gap: 10 },
  viewfinderHint: {
    fontFamily: FONT.sans,
    fontSize: 12,
    color: 'rgba(126,221,227,0.45)',
    letterSpacing: 0.3,
  },
  pulseRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(126,221,227,0.30)',
  },
  outputBox: {
    backgroundColor: COLOR.bgPage,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.borderIdle,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
    minHeight: 56,
    justifyContent: 'center',
  },
  outputLabel: {
    fontFamily: FONT.sans,
    fontSize: 9,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  outputText: {
    fontFamily: FONT.serif,
    fontSize: 15,
    color: COLOR.inkPrimary,
    letterSpacing: -0.1,
  },
  outputTextMuted: {
    color: COLOR.inkFaint,
    fontFamily: FONT.sans,
    fontSize: 13,
    fontStyle: 'italic',
  },
  startBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLOR.tealLight,
    borderRadius: RADIUS.md,
    height: 52,
    gap: 10,
  },
  startBtnText: {
    fontFamily: FONT.sans,
    fontSize: 15,
    fontWeight: '700',
    color: COLOR.tealDeep,
    letterSpacing: 0.2,
  },
  stopBtn: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
    borderColor: '#FECACA',
  },
  stopBtnText: { color: '#EF4444' },

  // ── Section Label ─────────────────────────────────────────────────────────────
  sectionLabel: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },

  // ── Phrasebook Card ───────────────────────────────────────────────────────────
  phrasebookCard: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    flexDirection: 'row',
    overflow: 'hidden',
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
    elevation: 3,
  },
  phrasebookCardBody: {
    flex: 1,
    padding: 18,
  },
  phrasebookCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  phrasebookIconWrap: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phrasebookFslBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.pill,
    backgroundColor: 'rgba(10,155,170,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
  },
  phrasebookFslBadgeText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.tealBright,
    letterSpacing: 0.8,
  },
  phrasebookCardTitle: {
    fontFamily: FONT.serif,
    fontSize: 17,
    color: COLOR.inkPrimary,
    letterSpacing: -0.2,
    marginBottom: 4,
  },
  phrasebookCardSub: {
    fontFamily: FONT.sans,
    fontSize: 12,
    color: COLOR.inkFaint,
    lineHeight: 17,
    marginBottom: 14,
  },
  phrasebookChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  phrasebookChip: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: RADIUS.pill,
    backgroundColor: COLOR.bgPage,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
  },
  phrasebookChipText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '600',
    color: COLOR.inkMuted,
    letterSpacing: 0.3,
  },
  phrasebookChipMore: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: RADIUS.pill,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
  },
  phrasebookChipMoreText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.tealBright,
    letterSpacing: 0.2,
  },
  phrasebookOpenRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  phrasebookOpenText: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '700',
    color: COLOR.tealBright,
    letterSpacing: 0.2,
  },

  // Decorative right panel
  phrasebookCardDeco: {
    width: 72,
    backgroundColor: 'rgba(10,155,170,0.04)',
    borderLeftWidth: 1,
    borderLeftColor: COLOR.borderCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  decoCircleOuter: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(10,155,170,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  decoCircleInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(10,155,170,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Quick Actions ─────────────────────────────────────────────────────────────
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  quickCard: {
    width: (W - 50) / 2,
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  quickIconWrap: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLabel: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.inkPrimary,
    lineHeight: 16,
  },
  quickSublabel: {
    fontFamily: FONT.sans,
    fontSize: 10,
    color: COLOR.inkFaint,
    marginTop: 2,
  },

  // ── Misc (kept for RecentRow compatibility) ───────────────────────────────────
  card: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    overflow: 'hidden',
    marginBottom: 8,
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  recentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.borderCard,
  },
  recentIconWrap: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recentSign: {
    fontFamily: FONT.sans,
    fontSize: 14,
    fontWeight: '700',
    color: COLOR.inkPrimary,
  },
  recentTranslation: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    marginTop: 1,
  },
  recentTime: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    fontWeight: '500',
  },
  viewAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    gap: 5,
  },
  viewAllText: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.tealBright,
    letterSpacing: 0.2,
  },
});