// PhrasebookStyle.js
import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLOR, FONT, RADIUS, WINDOW_WIDTH as W } from './theme';

export const phrasebookStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLOR.bgPage,
  },

  // ── Header ──────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: COLOR.tealDeep,
    paddingTop: Platform.OS === 'ios' ? 60 : 44,
    paddingBottom: 20,
    paddingHorizontal: 24,
    borderBottomLeftRadius: RADIUS.xl,
    borderBottomRightRadius: RADIUS.xl,
    overflow: 'hidden',
  },
  headerBlob: {
    position: 'absolute',
    top: -W * 0.2,
    right: -W * 0.1,
    width: W * 0.5,
    height: W * 0.5,
    borderRadius: W * 0.25,
    backgroundColor: 'rgba(10,155,170,0.13)',
  },
  headerEyebrow: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.tealLight,
    letterSpacing: 1.8,
    marginBottom: 4,
  },
  headerTitle: {
    fontFamily: FONT.serif,
    fontSize: 26,
    color: '#FFFFFF',
    letterSpacing: -0.4,
    marginBottom: 4,
  },
  headerSub: {
    fontFamily: FONT.sans,
    fontSize: 12,
    color: 'rgba(255,255,255,0.50)',
    marginBottom: 16,
  },

  // ── Search ───────────────────────────────────────────────────────────────────
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    height: 42,
  },
  searchInput: {
    flex: 1,
    fontFamily: FONT.sans,
    fontSize: 14,
    color: '#FFFFFF',
    paddingVertical: 0,
  },

  // ── Category Pills ────────────────────────────────────────────────────────────
  pillsWrap: {
    paddingTop: 16,
    paddingBottom: 4,
  },
  pillsContent: {
    paddingHorizontal: 20,
    gap: 8,
    flexDirection: 'row',
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: RADIUS.pill,
    backgroundColor: COLOR.bgCard,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
  },
  categoryPillActive: {
    backgroundColor: COLOR.tealLight,
    borderColor: COLOR.tealBright,
  },
  categoryPillText: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.inkFaint,
  },
  categoryPillTextActive: {
    color: COLOR.tealDeep,
  },
  favPillActive: {
    backgroundColor: '#FFF0F0',
    borderColor: '#FECACA',
  },
  favPillText: {
    color: '#EF4444',
  },

  // ── Pain Scale Strip ──────────────────────────────────────────────────────────
  painScaleStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  painScaleStripText: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.inkMuted,
    flex: 1,
  },
  painScaleMini: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  painDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },

  // ── Phrase List ───────────────────────────────────────────────────────────────
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 100,
    gap: 10,
  },
  phraseCard: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  phraseCardLeft: {
    flex: 1,
  },
  fslLabel: {
    fontFamily: FONT.serif,
    fontSize: 16,
    color: COLOR.inkPrimary,
    letterSpacing: -0.1,
    marginBottom: 2,
  },
  englishLabel: {
    fontFamily: FONT.sans,
    fontSize: 12,
    color: COLOR.tealBright,
    fontWeight: '600',
    marginBottom: 1,
  },
  tagalogLabel: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    fontStyle: 'italic',
  },
  favBtn: {
    padding: 4,
    marginLeft: 8,
  },

  // ── Queue Strip ───────────────────────────────────────────────────────────────
  queueStrip: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLOR.tealDeep,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: Platform.OS === 'ios' ? 28 : 52,
    gap: 10,
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    height: 100,
  },
  queueLabel: {
    fontFamily: FONT.sans,
    fontSize: 9,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.50)',
    letterSpacing: 1,
    minWidth: 60,
  },
  queueChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLOR.tealLight,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 6,
  },
  queueChipText: {
    fontFamily: FONT.sans,
    fontSize: 11,
    fontWeight: '700',
    color: COLOR.tealDeep,
  },
  queueShowBtn: {
    backgroundColor: COLOR.tealLight,
    borderRadius: RADIUS.md,
    paddingHorizontal: 16,
    paddingVertical: 8,
    minWidth: 54,
    alignItems: 'center',
  },
  queueShowText: {
    fontFamily: FONT.sans,
    fontSize: 13,
    fontWeight: '700',
    color: COLOR.tealDeep,
  },

  // ── Empty State ───────────────────────────────────────────────────────────────
  emptyWrap: {
    alignItems: 'center',
    paddingTop: 60,
    gap: 8,
  },
  emptyText: {
    fontFamily: FONT.serif,
    fontSize: 17,
    color: COLOR.inkMuted,
  },
  emptyHint: {
    fontFamily: FONT.sans,
    fontSize: 13,
    color: COLOR.inkFaint,
  },

  // ── Modal Overlay ─────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(13,61,64,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  modalCard: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.xl,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
    elevation: 10,
  },
  modalCatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLOR.tealGlow,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 14,
  },
  modalCatText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.tealBright,
    letterSpacing: 0.8,
  },
  modalEyebrow: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1.4,
    marginBottom: 10,
  },
  modalFSL: {
    fontFamily: FONT.serif,
    fontSize: 34,
    color: COLOR.inkPrimary,
    letterSpacing: -0.6,
    textAlign: 'center',
    marginBottom: 8,
  },
  modalEnglish: {
    fontFamily: FONT.sans,
    fontSize: 15,
    fontWeight: '600',
    color: COLOR.tealBright,
    textAlign: 'center',
    marginBottom: 4,
  },
  modalTagalog: {
    fontFamily: FONT.sans,
    fontSize: 13,
    color: COLOR.inkFaint,
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 24,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  modalBtnOutline: {
    flex: 1,
    height: 46,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: COLOR.borderIdle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnOutlineText: {
    fontFamily: FONT.sans,
    fontSize: 14,
    fontWeight: '600',
    color: COLOR.inkMuted,
  },
  modalBtnFill: {
    flex: 1,
    height: 46,
    borderRadius: RADIUS.md,
    backgroundColor: COLOR.tealLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  modalBtnFillText: {
    fontFamily: FONT.sans,
    fontSize: 14,
    fontWeight: '700',
    color: COLOR.tealDeep,
  },

  // ── Queue Display Modal ───────────────────────────────────────────────────────
  queueDisplayList: {
    gap: 6,
    marginVertical: 12,
    alignItems: 'center',
  },
  queueDisplayPhrase: {
    fontFamily: FONT.serif,
    fontSize: 24,
    color: COLOR.inkPrimary,
    textAlign: 'center',
  },

  // ── Pain Scale Modal ──────────────────────────────────────────────────────────
  painModalTitle: {
    fontFamily: FONT.serif,
    fontSize: 22,
    color: COLOR.inkPrimary,
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  painModalSub: {
    fontFamily: FONT.sans,
    fontSize: 12,
    color: COLOR.inkFaint,
    marginBottom: 20,
    textAlign: 'center',
  },
  painGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 16,
  },
  painBtn: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.sm,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  painBtnNum: {
    fontFamily: FONT.serif,
    fontSize: 18,
    fontWeight: '700',
  },
  painResult: {
    borderWidth: 1.5,
    borderRadius: RADIUS.md,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 2,
  },
  painResultNum: {
    fontFamily: FONT.serif,
    fontSize: 28,
    letterSpacing: -0.4,
  },
  painResultDesc: {
    fontFamily: FONT.sans,
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.inkFaint,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
});