// TranslatorScreenStyle.js

import { StyleSheet, Platform } from 'react-native';
import { COLOR, FONT, RADIUS, WINDOW_WIDTH as W } from './theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: COLOR.bgPage,
  },

  // ── Decorative page background (layered soft blobs, sits behind ScrollView) ─
  bgLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  bgBlobTopRight: {
    position: 'absolute',
    top: -W * 0.25,
    right: -W * 0.3,
    width: W * 0.9,
    height: W * 0.9,
    borderRadius: W * 0.45,
    backgroundColor: 'rgba(10,155,170,0.07)',
  },
  bgBlobMidLeft: {
    position: 'absolute',
    top: W * 0.55,
    left: -W * 0.35,
    width: W * 0.75,
    height: W * 0.75,
    borderRadius: W * 0.375,
    backgroundColor: 'rgba(217,119,6,0.045)',
  },
  bgBlobBottomRight: {
    position: 'absolute',
    bottom: -W * 0.3,
    right: -W * 0.2,
    width: W * 0.7,
    height: W * 0.7,
    borderRadius: W * 0.35,
    backgroundColor: 'rgba(10,155,170,0.05)',
  },

  // ── Permission / empty states ─────────────────────────────────────────────
  centeredFill: {
    flex: 1,
    backgroundColor: COLOR.bgPage,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: RADIUS.md,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontFamily: FONT.serif,
    fontSize: 20,
    color: COLOR.inkPrimary,
    letterSpacing: -0.3,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyBody: {
    fontFamily: FONT.sans,
    fontSize: 14,
    color: COLOR.inkFaint,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: COLOR.tealDeep,
    paddingTop: Platform.OS === 'ios' ? 60 : 44,
    paddingBottom: 18,
    paddingHorizontal: 24,
    overflow: 'hidden',

  },
  headerBlob: {
    position: 'absolute',
    top: -W * 0.2,
    right: -W * 0.15,
    width: W * 0.55,
    height: W * 0.55,
    borderRadius: W * 0.275,
    backgroundColor: 'rgba(10,155,170,0.13)',
  },
  headerBlobSecondary: {
    position: 'absolute',
    bottom: -W * 0.25,
    left: -W * 0.18,
    width: W * 0.45,
    height: W * 0.45,
    borderRadius: W * 0.225,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerEyebrow: {
    fontFamily: FONT.sans,
    fontSize: 13,
    color: 'rgba(255,255,255,0.55)',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  headerTitle: {
    fontFamily: FONT.serif,
    fontSize: 28,
    color: COLOR.white,
    letterSpacing: -0.4,
    marginTop: 2,
  },
  headerSub: {
    fontFamily: FONT.sans,
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.62)',
    marginTop: 6,
    maxWidth: '78%',
    lineHeight: 17,
  },

  // ── Live badge ────────────────────────────────────────────────────────────
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    marginTop: 4,
  },
  liveBadgeActive: {
    backgroundColor: COLOR.greenSurface,
    borderColor: COLOR.greenBorder,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  liveDotActive: {
    backgroundColor: '#22C55E',
  },
  liveText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.70)',
    letterSpacing: 0.8,
  },
  liveTextActive: {
    color: COLOR.green,
  },

  // ── Scroll content ────────────────────────────────────────────────────────
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 48,
    gap: 16,
  },

  // ── Section heading (above groups of cards) ──────────────────────────────
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: -4,
  },
  sectionHeadingDash: {
    width: 14,
    height: 3,
    borderRadius: 2,
    backgroundColor: COLOR.tealLight,
  },
  sectionHeadingText: {
    fontFamily: FONT.sans,
    fontSize: 11,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },

  // ── Banner ────────────────────────────────────────────────────────────────
  bannerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(217,119,6,0.08)',
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: 'rgba(217,119,6,0.20)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  bannerCardError: {
    backgroundColor: COLOR.redSurface,
    borderColor: COLOR.redBorder,
  },
  bannerIconWrap: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    backgroundColor: 'rgba(217,119,6,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerIconWrapError: {
    backgroundColor: 'rgba(220,38,38,0.14)',
  },
  bannerText: {
    flex: 1,
    fontFamily: FONT.sans,
    fontSize: 13,
    fontWeight: '600',
    color: COLOR.amber,
  },
  bannerTextError: {
    color: COLOR.red,
  },

  // ── Cards ─────────────────────────────────────────────────────────────────
  card: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    overflow: 'hidden',
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  cardMedical: {
    borderColor: 'rgba(217,119,6,0.30)',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardIconWrap: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontFamily: FONT.serif,
    fontSize: 16,
    color: COLOR.inkPrimary,
    letterSpacing: -0.2,
  },
  cardSub: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    marginTop: 1,
  },

  // ── Status chip shown inside the camera card header (frames-detected, etc.) ─
  cardHeaderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: RADIUS.pill,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.18)',
  },
  cardHeaderChipText: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.tealDeep,
    letterSpacing: 0.3,
  },

  // ── Viewfinder ────────────────────────────────────────────────────────────
  viewfinderWrap: {
    height: 280,
    backgroundColor: '#0D2B2E',
    overflow: 'hidden',
    marginHorizontal: 0,
    borderBottomLeftRadius: RADIUS.lg,
    borderBottomRightRadius: RADIUS.lg,
    position: 'relative',
  },
  scanlineOverlay: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 14,
    bottom: 14,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  corner: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderColor: COLOR.tealLight,
    borderWidth: 2.5,
  },
  cornerTL: {
    top: 14, left: 14,
    borderRightWidth: 0, borderBottomWidth: 0,
    borderTopLeftRadius: 6,
  },
  cornerTR: {
    top: 14, right: 14,
    borderLeftWidth: 0, borderBottomWidth: 0,
    borderTopRightRadius: 6,
  },
  cornerBL: {
    bottom: 14, left: 14,
    borderRightWidth: 0, borderTopWidth: 0,
    borderBottomLeftRadius: 6,
  },
  cornerBR: {
    bottom: 14, right: 14,
    borderLeftWidth: 0, borderTopWidth: 0,
    borderBottomRightRadius: 6,
  },
  viewfinderHint: {
    position: 'absolute',
    bottom: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: RADIUS.pill,
    paddingVertical: 6,
  },
  viewfinderHintText: {
    fontFamily: FONT.sans,
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.85)',
    letterSpacing: 0.2,
  },

  // ── Prediction card ───────────────────────────────────────────────────────
  predictionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sectionLabel: {
    fontFamily: FONT.sans,
    fontSize: 9,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 4,
  },
  sectionLabelSpaced: {
    fontFamily: FONT.sans,
    fontSize: 9,
    fontWeight: '700',
    color: COLOR.inkFaint,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  predictionLabel: {
    fontFamily: FONT.serif,
    fontSize: 44,
    color: COLOR.inkPrimary,
    letterSpacing: -0.5,
    paddingHorizontal: 16,
    paddingTop: 2,
    paddingBottom: 4,
  },
  predictionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  predictionConf: {
    fontFamily: FONT.sans,
    fontSize: 13,
    color: COLOR.inkFaint,
  },
  confidenceTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLOR.tealGlow,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: COLOR.tealLight,
  },
  medicalTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLOR.amberSurface,
    borderRadius: RADIUS.pill,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginHorizontal: 16,
    marginBottom: 14,
    alignSelf: 'flex-start',
  },
  medicalTagText: {
    fontFamily: FONT.sans,
    fontSize: 11,
    fontWeight: '600',
    color: COLOR.amber,
  },

  // ── Output placeholder ────────────────────────────────────────────────────
  outputBox: {
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    borderStyle: 'dashed',
    paddingBottom: 22,
    minHeight: 96,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outputIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLOR.tealGlow,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  outputTextMuted: {
    fontFamily: FONT.sans,
    fontSize: 14,
    color: COLOR.inkFaint,
    fontStyle: 'italic',
    paddingHorizontal: 16,
    textAlign: 'center',
  },

  // ── Quick stats row (e.g. signs detected / session time) ─────────────────
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statChip: {
    flex: 1,
    backgroundColor: COLOR.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.borderCard,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'flex-start',
    gap: 4,
  },
  statChipValue: {
    fontFamily: FONT.serif,
    fontSize: 22,
    color: COLOR.inkPrimary,
    letterSpacing: -0.3,
  },
  statChipLabel: {
    fontFamily: FONT.sans,
    fontSize: 10,
    fontWeight: '600',
    color: COLOR.inkFaint,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // ── Tips card ─────────────────────────────────────────────────────────────
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  tipBullet: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLOR.tealGlow,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  tipText: {
    flex: 1,
    fontFamily: FONT.sans,
    fontSize: 13,
    color: COLOR.inkPrimary,
    lineHeight: 18,
  },
  divider: {
    height: 1,
    backgroundColor: COLOR.borderCard,
    marginHorizontal: 16,
  },

  // ── History rows ──────────────────────────────────────────────────────────
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
    gap: 12,
  },
  historyRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: COLOR.borderCard,
  },
  historyIconWrap: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    backgroundColor: COLOR.tealGlow,
    borderWidth: 1,
    borderColor: 'rgba(10,155,170,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyIconMedical: {
    backgroundColor: COLOR.amberSurface,
    borderColor: 'rgba(217,119,6,0.20)',
  },
  historyTextWrap: {
    flex: 1,
  },
  historySign: {
    fontFamily: FONT.sans,
    fontSize: 14,
    fontWeight: '700',
    color: COLOR.inkPrimary,
  },
  historyMedicalLabel: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.amber,
    marginTop: 1,
  },
  historyTime: {
    fontFamily: FONT.sans,
    fontSize: 11,
    color: COLOR.inkFaint,
    fontWeight: '500',
  },

  // ── Buttons ───────────────────────────────────────────────────────────────
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLOR.tealLight,
    borderRadius: RADIUS.md,
    height: 56,
    gap: 10,
    marginTop: 4,
    shadowColor: COLOR.tealDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
  },
  primaryBtnText: {
    fontFamily: FONT.sans,
    fontSize: 15,
    fontWeight: '700',
    color: COLOR.tealDeep,
    letterSpacing: 0.2,
  },
  stopBtn: {
    backgroundColor: COLOR.redSurface,
    borderWidth: 1.5,
    borderColor: COLOR.redBorder,
    shadowOpacity: 0,
    elevation: 0,
  },
  stopBtnText: {
    color: COLOR.red,
  },
});